# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  encoding: unicode
  database: haiku_development
  pool: 5
  username: paid_programmer

test: &test
  adapter: sqlite3
  encoding: unicode
  database: haiku_test
  pool: 5
  username: paid_programmer
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: haiku_production
  host: localhost
  pool: 5
  username: paid_programmer
  password: password
